If we can't find a colormap to replace, insert new one instead of leaking it
Found by Oracle's Parfait 2.2 static analyzer:

Error: Memory leak
   Memory leak [memory-leak] (CWE 401):
      Memory leak of pointer sc allocated with malloc(32)
        at line 421 of src/util.c in function 'InsertRGBColormap'.
          sc allocated at line 397 with malloc(32)
          sc leaks when replace != 0 at line 405.

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>